# Trading Bot Configuration
# Modify these settings to optimize performance and API usage

# API Rate Limiting (requests per minute) - Optimized for stability
rate_limits:
  oanda: 15          # Very conservative to avoid rate limits
  finnhub: 30        # Reduced
  newsapi: 500       # Reduced
  alpha_vantage: 3   # Reduced
  marketaux: 50      # Added
  yahoo_finance: 1000 # Added

# Request delays (seconds between API calls) - Increased for stability
api_delays:
  between_symbols: 1.5      # Increased wait between different symbols
  between_timeframes: 1.0  # Increased wait between different timeframes
  retry_delay: 3.0         # Increased base delay for retries

# OANDA API Configuration  
oanda:
  # Symbol mappings - try these formats in order
  symbol_mappings:
    EURUSD: ["EUR_USD", "EURUSD"]
    XAUUSD: ["XAU_USD", "XAUUSD", "GOLD"]
    BTCUSD: ["BTC_USD", "BTCUSD", "BTC"]
    NAS100: ["NAS100_USD", "NAS100", "NAS_USD"]
  
  # Alternative fallback APIs to try
  fallback_apis:
    - "yahoo_finance"
    - "alpha_vantage" 
    - "mock"

# Debugging
debug:
  log_api_requests: true   # Log all API requests
  mock_data_fallback: true # Use mock data when APIs fail
  
# Notifications
notifications:
  on_rate_limit: true     # Send notification when rate limited
  on_api_error: true      # Send notification on API errors